/**:
  ros__parameters:
    # Gains for sunray150 + SO3 controller
    uav_name: "sunray150_mid360"
    
    mass: 1.104

    gains/kx/x: 5.0
    gains/kx/y: 5.0
    gains/kx/z: 15.0

    gains/kv/x: 5.0
    gains/kv/y: 5.0
    gains/kv/z: 5.0

    gains/rot/x: 3.5
    gains/rot/y: 3.5
    gains/rot/z: 1.0

    gains/ang/x: 0.4
    gains/ang/y: 0.4
    gains/ang/z: 0.1

    kMaxTotalThrust: 23.0